config/routes.rb
Phoneapp::Application.routes.draw do
  
  get "search/index"

  resource :call_handler do
    member do
      get 'update_number'
      get 'conference_queue'
      get 'leave_message'
      post 'leave_message'
      get 'agent_information'
      get 'patch_agent'
      get 'unlock_agent'
    end
  end
  
  get "home", :to => "home#index"

  get "users/index"
  
  get "calls/index"
  
  

  devise_for :users 
  
  resources :users do
    collection do
      get 'sync_with_zendesk'
      post 'sync_with_zendesk'
      get 'sync_with_app'
      post 'sync_with_app'
      get 'prioritize'
      post 'prioritize'
      get 'search'
      post 'search'
    end
  end
  
  
  resources :calls do
    collection do
      get 'in_progress'
      get 'unresolved'
    end
    
    resources :comments
  end
  
  resources :systems
  
  resources :users, :path => '#/users/index'
  
  resources :zendesk_tickets
  
  resources :user_syncr

  root :to => 'home#index'

end

app/models/call.rb
module ZendeskCallMethods
  
  #links the call to its corresponding zendesk ticket for an agent to 
  #go view
  def zendesk_call_string(zendesk_id)
    if zendesk_id != nil
      url = "https://tmadar.zendesk.com/tickets/#{zendesk_id}"
    end
    return url
  end
  
  def zendesk_ticket_url
    return zendesk_call_string(zendesk_id)
  end
  
  #When a call is made by a customer, a new ticket will be added into
  #zendesk with default values
  def add_ticket
    new_zendesk = ZendeskTicket.new
    new_zendesk.subject = "Call from #{self.caller}"
    new_zendesk.status = "open"
    new_zendesk.priority = "high"
    new_zendesk.type = "problem"
    new_zendesk.description = "A call was made to us by #{self.caller} at #{self.received_at}."
    new_zendesk.save
    return new_zendesk.id
  end
  
  #Able to access the zendesk API through the Call object
  def zendesk_ticket
    ZendeskTicket.find(self.zendesk_id) if self.zendesk_id
  end
  
  #If an agent decides that at the end of the call that the
  #customer's issue has been solved, they may press a key
  # to "close" the call and change the status to "solved"
  def update_zendesk_ticket
    Thread.new do
      if self.needs_update
        ticket = zendesk_ticket
        ticket.group_id = 20310643
        ticket.assignee_id = 245140892
        ticket.status = DISPOSITION_MAPPINGS[self.disposition]
        ticket.save
        self.needs_update = nil
      end
    end
  end
  
end

class Call < ActiveRecord::Base
  include ZendeskCallMethods
  include HomeHelper
  
  DISPOSITIONS = ["Open", "Closed"]
  RINGCENTRAL_STATES = [ "queued", "ringing", "in-progress", "completed", "failed", "busy" "no-answer" ]
  DISPOSITION_MAPPINGS = { "Open" => "open", "Closed" => "solved" }

  attr_accessible :caller, :received_at, :duration, :twilio_call_sid,
                  :zendesk_id, :rescheduled_to, :status, :comment, :recording,
                  :disposition, :last_comment, :user_id, :rescheduled_to_nice
  
  attr_accessor :needs_update
  
  has_many :comments, :autosave => true, :dependent => :destroy
  belongs_to :user
  
  before_save :toggle_update
  after_save :update_zendesk_ticket
  
  validates :caller, :presence => true 
  validates :disposition, :inclusion => { :in => DISPOSITIONS }, :presence => true
  validates :status, :inclusion => { :in => RINGCENTRAL_STATES }, :presence => true
  
  
  #A Call object will be created and given params from Twilio.
  #If a customer calls, a zendesk ticket will be created.

  def self.received(params)
    if params and params[:Caller]
      new_call = self.new
      new_call.caller = params[:From].sub("+","")
      new_call.received_at = Time.now
      new_call.twilio_call_sid = params[:CallSid]
      new_call.status =  params[:CallStatus]
      if (user = User.where(["phone = ?", new_call.caller]).first)
        new_call.user = user
        if new_call.user.availability == "Yes"
          new_call.disposition = "Online"
        else
          new_call.disposition = "Offline"
        end
      else
        zendesk_id = new_call.add_ticket
        new_call.zendesk_id = zendesk_id
      end
      new_call.save
      return new_call
    end
  end
  
  #Creates a new Call object so that the agent can be patched in w/ the
  #calling customer
  def self.received_from_agent(params)
    if params and params[:Caller]
      new_call = self.new
      new_call.caller = params[:To].sub("+","")
      puts new_call.caller
      new_call.received_at = Time.now
      new_call.twilio_call_sid = params[:CallSid]
      new_call.status =  params[:CallStatus]
      if (user = User.where(["phone = ?", new_call.caller]).first)
        new_call.user = user
      end
      customer_call = self.find(params[:call_id]) if params[:call_id]
      new_call.zendesk_id = customer_call.zendesk_id
      new_call.save
      return new_call
    end
  end
  
  #When a customer's call is completed, further twilio information
  #regarding the call will be stored to the Call object.
  def self.update_incomplete
    calls = self.where("status != ?", "completed")
    calls.each do |call|
      twilio_call = $twilio_client.account.calls.get(call.twilio_call_sid)
      call.received_at = twilio_call.start_time
      call.duration = twilio_call.duration
      call.status = twilio_call.status
      if twilio_call.recordings.list.first
        call.recording = twilio_call.recordings.list.first.wav
      end
      call.save
    end
  end

  #Toggle agent's status when they call into the system
  def change_disposition!
    if self.disposition == "Offline"
      self.disposition = "Online"
    else
      self.disposition = "Offline"
    end
    self.save
  end
  
  #Assigns a specific agent from User to a call
  def assign_agent(user_id)
    found = User.where(:id => user_id)
    if found.empty? == true
      found = "Assign"
      return found
    else
      return found[0]["name"]
    end
  end
  
  #Method to see all the calls that are in-progress or ringing
  #for the AJAX table to appear on the Home page
  def self.in_progress
    where(:status => ["in-progress", "ringing"], :user_id => nil)
  end
  
  #A queue of available agents will be made so that when a customer
  #calls, the 1st agent in the queue will be contacted.
  #If failed to be reached, the next agent in the queue will be
  #contacted, looping until the queue has been emptied or an agent
  #has been patched in.
  def patch_agent
    if not $redis.exists("call:#{self.id}:started_calling_agents")
      $redis.setex("call:#{self.id}:started_calling_agents", 600, "1")
      User.available.each do |user|
        $redis.rpush("call:#{self.id}:agents_to_call", user.id)
      end
      $redis.expire("call:#{self.id}:agents_to_call", 600)
    end   
    
    if $redis.exists("call:#{self.id}:started_calling_agents")
      id = $redis.lpop("call:#{self.id}:agents_to_call")
      if id       
        user = User.where(:id => id).first
        user.accept_call(self)
      else
        $twilio_client.account.calls.get(self.twilio_call_sid).redirect_to("http://184.183.31.238:3000/call_handler/leave_message.xml?sorry=true")
      end
    end
  end
  
  def agents_to_call
    User.where(:id => $redis.lrange("call:#{self.id}:agents_to_call", 0, $redis.llen("call:#{self.id}:agents_to_call")+1))
  end
  
  #If a recording for a call exists, a link will be generated
  #in the View Call Info section. Otherwise, "No Message" will appear.
  def recording?
    not self.recording.nil?
  end
  
  #Checks to see whether or not an agent has changed the call status
  #before deciding to "save" to AR
  def toggle_update
    if self.disposition_changed?
      self.needs_update = true
    end
  end
  
  #Method to find all the calls with a "Closed" disposition
  def self.solved
    where("disposition = ? ", "Closed")
  end
  
  def rescheduled_to_nice=(value)
    value = cleanup_time_string(value)
    
    begin
      write_attribute(:rescheduled_to, Time.parse(value))
    rescue
      errors.add(:rescheduled_to, "couldn't be understood")
    end
    
    puts self.errors.inspect
  end
  
  def rescheduled_to_nice
    send(:rescheduled_to)
  end
  
  # def received_at=(value)
  #   value = cleanup_time_string(value)
  #   super(Time.parse(value))
  # end
  # 
  # def received_at
  #   if super
  #     return nice_time(super.localtime)
  #   else
  #     return nil
  #   end
  # end
  
  def rescheduled_to=(value)
    value = cleanup_time_string(value.localtime)
    super(Time.parse(value))
  end
  
  def rescheduled_to
    if read_attribute(:rescheduled_to)
      return nice_time(super.localtime)
    else
      return nil
    end
  end
      
  def cleanup_time_string(value)
    value = value.downcase.gsub(/yesterday/, (Time.now - 1.day).localtime.to_date.strftime("%m/%d/%Y"))
    value = value.downcase.gsub(/today/, (Time.now).localtime.to_date.strftime("%m/%d/%Y"))
    value = value.downcase.gsub(/tomorrow/, (Time.now + 1.day).localtime.to_date.strftime("%m/%d/%Y"))
    
    begin
      day_string = value.match(/\D+/).to_s
      value = value.downcase.gsub(day_string, Date.parse(day_string).strftime("%m/%d/%Y") + " ")
    rescue ArgumentError => e
      errors.add(:rescheduled_to, "couldn't be understood")
    end

    return value
  end
  
  def received_at_original
    read_attribute(:received_at)
  end
  
  
end

app/controllers/calls_controller.rb
class CallsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :setup_users, :except => [ :in_progress ]
  
  def setup_users
    @users = User.all
  end
  
  #shows the comprehensive list of calls
  def index
    @calls = Call.rsend(*sort_order_for_calls).paginate page: params[:page], per_page: 10
    respond_to do |format|
      format.html { render :layout => "#{@empty ? "empty" : "application"}"}
      format.js
      format.xml { render 'index.xml.builder' }
      format.json
    end
  end
  
  def unresolved
    @calls = Call.where(:disposition => "Open", :status => "completed", :user_id => nil).paginate page: params[:page], order: 'created_at desc', per_page: 5
    respond_to do |format|
      format.html
      format.js
    end
  end
  
  #Modal view of specific info of the call
  #giving reschedule time, comments, etc.
  def show
    @call = Call.where(:id => params[:id]).first
    respond_to do |format|
      format.html
      format.xml { render :xml => @call }
      format.json { render :json => @call }
      format.js
    end
  end

  #Allows for the action of assigning agents to the call, etc.
  def update
    @call = Call.find(params[:id])
    @call.update_attributes(params[:call])
    respond_to do |format|
        format.html
        format.json { render :json => @call.to_json(:include => [ :user ]) }
        format.js
    end
  end
  
  #If a call by a customer is "ringing" or "in-progress", it will
  #be shown on the Home page in AJAX
  def in_progress
    @calls = Call.in_progress
    respond_to do |format|
      format.json { render :json => @calls }
      format.xml { render :xml => @calls }
      format.js
    end
  end
  
  def sort_order_for_calls
    if Call.column_names.include?(params[:sort_by])
      if params[:sort_by] == "caller"
        return [[:order, "replace(replace(replace(#{params[:sort_by]}, '-', ''), '+1', ''), '+', '') #{params[:direction] == "1" ? "asc" : "desc"}"]]
      elsif params[:sort_by] == "user_id"
        return [[:joins, "LEFT OUTER JOIN users on calls.user_id = users.id"], [:order, "users.name #{params[:direction] == "1" ? "asc" : "desc"}"]]
      else
        return [[:order, "#{params[:sort_by]} #{params[:direction] == "1" ? "asc" : "desc"}"]]
      end
    else
      return [[:order, "created_at desc"]]
    end
  end
  
    
end

app/helpers/call_helper.rb
module CallHelper
end

app/views/calls/_calls_partial.html.erb
	<table class="table call-padded table-clickable" call-ref="<%= call_ref ||= calls_path %>" call-update-target="<%= call_update_target ||= "" %>" <% if params[:page] %>page="<%= params[:page] %>"<% end %>>
		<h1><%= title ||= "No title defined" %></h1>
		<thead>
			<tr>
				<th class="sort-header" id="time" column-name="received_at" style="width: 15%" <%= th_sort_modifier("received_at").html_safe %>><span class="icon-calendar"></span> Time<%= th_span_modifier("received_at").html_safe %></th>
				<th class="sort-header" id="duration" style="width: 16%" <%= th_sort_modifier("duration").html_safe %>><span class="icon-signal"></span> Duration <%= th_span_modifier("duration").html_safe %></th>
				<th class="sort-header" id="phone" column-name="caller" style="width: 18%" <%= th_sort_modifier("caller").html_safe %>><span class="icon-hand-right"></span> Callback #<%= th_span_modifier("caller").html_safe %></th>
				<th class="sort-header" id="status" style="width: 16%" <%= th_sort_modifier("status").html_safe %>><span class="icon-ok-sign" ></span> Call Status <%= th_span_modifier("status").html_safe %></th>
				<th class="sort-header" id="disposition" style="width: 16%" <%= th_sort_modifier("disposition").html_safe %>><span class="icon-tag"></span> Disposition <%= th_span_modifier("disposition").html_safe %></th>
				<th class="sort-header" id="assign" column-name="user_id" style="width: 19%" <%= th_sort_modifier("user_id").html_safe %>><span class="icon-user"></span> Assigned To <%= th_span_modifier("user_id").html_safe %></th>			
			</tr>
		</thead>
		<tbody>	
	 <% calls.each do |call| %>
			<tr id="call_<%= call.id %>">
				<td class="call_table" onclick="displayCall(<%= call.id %>)"><%= nice_time(call.received_at) %></td>
				<td class="call_table" onclick="displayCall(<%= call.id %>)"><%= "#{call.duration} #{call.duration != 1 ? "seconds" : "second"}" %></td>
				<td class="call_table" onclick="displayCall(<%= call.id %>)"><%= number_to_phone(call.caller.gsub(/^1/,'')) %></td>
				<td class="call_table" onclick="displayCall(<%= call.id %>)"><%= call.status.humanize if call.status %></td>
				<td>
					<div class="btn-group">
						<button class="btn btn-small dropdown-toggle call_disposition" data-toggle="dropdown" id="call_<%= call.id %>_disposition"><%= call.disposition %> <span class="caret"></span></button>
				    <ul class="dropdown-menu">
						<% Call::DISPOSITIONS.each do |disposition| %>
				      <li><%= link_to_function "#{disposition}", "updateStateOfCall(#{call.id}, '#{escape_javascript(disposition)}')" %></li>
						<% end %>
				    </ul>
					</div>
				</td>
				<td>
					<div class="btn-group">
						<button class="btn btn-small dropdown-toggle" data-toggle="dropdown" id="call_<%= call.id %>_assignee" style="width: 100%; text-align: left;"><%= call.user ? (call.user.name ? call.user.name : call.user.email) : "- Unassigned - " %> <span class="caret" style="float: right"></span></button>
				    <ul class="dropdown-menu">
						<% @users.each do |user| %>
				      <li><%= link_to_function "#{user.name ? user.name : user.email}", "updateAssignmentOfCall(#{call.id}, '#{user.id}', '#{user.name ? user.name : user.email}')" %></li>
						<% end %>
				    </ul>
					</div>
				</td>
			</tr>
			<% end %>
			</tbody>
	</table>
<%= will_paginate(calls, { :renderer => BootstrapPagination::Rails, :extra_attributes => { "data-remote" => true }, :call_div_id => call_ref }) %>	

<script>
// $(document).ready(function() { 
// 	$('.pagination a').attr('data-remote', 'true');
// });
</script>

app/views/calls/_comments.html.erb
<% if not @call.comments.empty? %>
<h3>Comments</h3>
<%= render @call.comments %>
<% end %>

app/views/calls/_form.html.erb
<%= form_for([call, call.comments.build], :html => { :class => "form-horizontal", :style => "padding-top: 10px"}, :remote => true) do |f|%>

<%= f.text_area :body, :cols => 100, :rows =>5, :style => "width: 97%" %>

<%= f.button :class => "btn btn-large", :style => "margin-top: 10px" %>

<% end %>

app/views/calls/_modal.html.erb
<div class="call-partial">
	
<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal">×</button>
	<h3>
		Call Information (#<%= call.id %>)
	</h3>
</div>
<div class="modal-body">
	
	
	<table class="table table-bordered table-condensed table-striped">
		<tr>
			<th>Received</th>
			<th>Callback #</th>
			<th>Duration</th>
			<th>Status</th>
		</tr>
		<tr>
			<td><%= nice_time call.received_at %></td>
			<td><%= number_to_phone(call.caller.gsub(/^1/, "")) %></td>
			<td><%= call.duration %> seconds</td>
			<td><%= call.status.humanize %></td>
		</tr>
	</table>
	

	
	<div class="control-group form-horizontal">
		<label class="control-label" for="modal_call_<%= call.id %>_disposition">Status</label>
		<div class="controls">
			<div class="btn-group">
				<button class="btn btn-small dropdown-toggle" data-toggle="dropdown" id="modal_call_<%= call.id %>_disposition" style="width: 50%; text-align: left;"><%= call.disposition %> <span class="caret"></span></button>
		    <ul class="dropdown-menu">
				<% Call::DISPOSITIONS.each do |disposition| %>
		      <li><%= link_to_function "#{disposition}", "modalUpdateStateOfCall(#{call.id}, '#{escape_javascript(disposition)}')" %></li>
				<% end %>
		    </ul>
			</div>
		</div>
	</div>

	<div class="control-group form-horizontal">
		<label class="control-label" for="modal_call_<%= call.id %>_assignee">Assignee</label>
		<div class="controls">
			<div class="btn-group">
				<button class="btn btn-small dropdown-toggle" data-toggle="dropdown" id="modal_call_<%= call.id %>_assignee" style="width: 100%; text-align: left;"><%= call.user ? (call.user.name ? call.user.name : call.user.email) : "- Unassigned - " %> <span class="caret" style="float: right"></span></button>
		    <ul class="dropdown-menu">
				<% @users.each do |user| %>
		      <li><%= link_to_function "#{user.name ? user.name : user.email}", "updateAssignmentOfCall(#{call.id}, '#{user.id}', '#{user.name ? user.name : user.email}')" %></li>
				<% end %>
		    </ul>
			</div>
		</div>
	</div>

	<%= render 'time', :call => @call %>

  <div class="control-group form-horizontal">
		<div class="controls">
			<% if @call.recording? %>
				<%= link_to "<span class=\"icon-play\"></span> Play Recording".html_safe, @call.recording, { :class => "btn btn-large", :type => "button" } %>
			<% end %>
			<% if @call.zendesk_id %>
				<%= link_to "<span class=\"icon-share-alt\"></span>  Open Ticket".html_safe, @call.zendesk_ticket_url, { :class => "btn btn-large", :type => "button" } %>
			<% end %>
		</div>
	</div>
	
	<div id="comments">
		<%= render 'comments', :call => call %>
	</div>
	
	<%= render 'form', :call => call %>

</div>
<div class="modal-footer">
	<a href="#" class="btn btn-primary" data-dismiss="modal">Close</a>
</div>

</div>

app/views/calls/_special.html.erb
<% @calls.each do |call| %>
<div class="modal hide fade" id="callModal_<%= call.id %>">
	<%= render 'modal', :call => call %>
</div>
<% end %>

app/views/calls/_time.html.erb
<%= form_for(call, :url => call_path(call), :method => :put, :html => { :class => "form-horizontal" }, :remote => true) do |f|%>
	<div class="control-group form-horizontal">
		<label class="control-label" for="modal_call_<%= call.id %>_time">Reschedule to... </label>
		<div class="controls">
			<%= text_field :call, :rescheduled_to_nice, { :placeholder => "Enter a time here", :class => "input-medium search-query", :id => "modal_call_#{call.id}_time" } %>  <%= f.submit "Reschedule", { :class => "btn" } %>
		</div>
	</div>
<% end %>

app/views/calls/_update_table.js.erb
$("#<%= call_div_id ||= "unresolved_calls" %>").html("<%= escape_javascript(render('calls/calls_partial.html', :title => (title ||= ""), :calls => (calls ||= @calls), :call_ref => (call_ref ||= calls_path), :call_update_target => (call_div_id ||= ""))) %>");

app/views/calls/index.html.erb
<div id="all_calls" class="calls buffer">
	<%= render 'calls_partial', :title => "", :calls => @calls, :call_ref => calls_path(:format => :js), :call_update_target => "all_calls" %>
</div>

<%= render 'home/call_modal' %>

app/views/calls/index.js.erb
<%= render 'update_table', :call_div_id => "all_calls", :call_ref => request.env['PATH_INFO'], :title => params[:title]  %>

app/views/calls/new.html.erb
<div class="new_comment">
	<h1>New Comment</h1>
	<%= render 'form' %>
</div>

app/views/calls/show.html.erb
<div class="content" id="showCall">
		<h3>Call Record</h3>


	<table class="table table-bordered table-condensed table-striped call-padded">
		<tr>
			<th>Call ID #</th>
			<td><%= @call.id %></td>
		</tr>
		<tr>
			<th>Time of Call</th>
			<td><%= @call.received_at %></td>
		</tr>
		<tr>
			<th>Callback #</th>
			<td><%= @call.caller %></td>
		</tr>
		<tr>
			<th>Duration</th>
			<td><%= "#{@call.duration} seconds" %></td>
		</tr>
		<tr>
			<th>Call Status</th>
			<td><%= @call.status %></td>
		</tr>
		<tr>
			<th>Disposition</th>
			<td><%= @call.disposition %></td>
		</tr>
		<tr>
			<th>Assigned To</th>
			<td><%= @call.assign_agent(@call.user_id) %></td>
		</tr>
		<tr>
			<th>Reschedule Time</th>
			<td>
				<%= render 'time', :call => @call %>
			</td>
		</tr>
		<tr>
			<th>Audio Message</th>
			<td>
				<% if @call.recording  != nil %>
					<%= link_to "Link", @call.recording %>
				<% else %>
					No Message
				<% end %>
			</td>
		</tr>
		<tr>
			<th>Zendesk Ticket</th>
			<td>
				<%= link_to "Zendesk Ticket", @call.zendesk_call_string(@call.zendesk_id)%>
			</td>
		</tr>
		<tr>
			<th>Last Comment</th>
			<td><%= @call.last_comment%></td>
		</tr>
	</table>
	
	<div id="comments">
		<%= render 'comments', :call => @call %>
	</div>
	<div class="new_comment">
		<h2>Add a Comment</h2>
		<%= render 'form', :call => @call %>
	</div>
</div>

app/views/calls/show.js.erb
$("#callModal").html("<%= escape_javascript(render('modal', :call => @call)) %>");
$('#callModal').modal('show');

app/views/calls/unresolved.js.erb
$("#<%= params[:call_id] ||= "unresolved_calls" %>").html("<%= escape_javascript(render('calls/calls_partial', :title => "Unresolved Calls", :calls => @calls, :call_ref => unresolved_calls_path(:format => :js), :call_update_target => "unresolved_calls"))%>");

app/views/calls/update.js.erb
$("#callModal").html("<%= escape_javascript(render('modal', :call => @call)) %>");
<% if @call.errors.size > 0 %>
$("#callModal .modal-body").prepend("<div class=\"alert alert-error\">Uh oh.</div>");
<% else %>
$("#callModal .modal-body").prepend("<div class=\"alert alert-success\">You have successfully saved the call record.</div>");
<% end %>