config/routes.rb
Phoneapp::Application.routes.draw do
  
  get "search/index"

  resource :call_handler do
    member do
      get 'update_number'
      get 'conference_queue'
      get 'leave_message'
      post 'leave_message'
      get 'agent_information'
      get 'patch_agent'
      get 'unlock_agent'
    end
  end
  
  get "home", :to => "home#index"

  get "users/index"
  
  get "calls/index"
  
  

  devise_for :users 
  
  resources :users do
    collection do
      get 'sync_with_zendesk'
      post 'sync_with_zendesk'
      get 'sync_with_app'
      post 'sync_with_app'
      get 'prioritize'
      post 'prioritize'
      get 'search'
      post 'search'
    end
  end
  
  
  resources :calls do
    collection do
      get 'in_progress'
      get 'unresolved'
    end
    
    resources :comments
  end
  
  resources :systems
  
  resources :users, :path => '#/users/index'
  
  resources :zendesk_tickets
  
  resources :user_syncr

  root :to => 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  include CanCan::Ability
  
  @@router = UrlOutputter.new
  
  AVAILABILITY = ["Yes", "No"]
  CONTACT = ["Email", "Text"]
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :email, :password, :password_confirmation, :remember_me, :name,
                  :phone, :priority, :availability, :means_of_contact, :admin
  
  has_many :calls
  

  #Toggle method which allows an agent to switch their availability
  #status when calling in
  def toggle_availability!
    if not self.available? or self.availablity == nil
      self.availability = "Yes"
    else
      self.availability = "No"
    end
    self.save
  end
  
  #Check to see if the agent is available and not in a call
  def available?
    if self.availability != "Yes" and not locked?
      return false
    end
    return true
  end
  
  #Find all agents who are available
  def self.available
    order("priority").where(:availability => "Yes")
  end
  
  #The twilio object will perform a method connecting an agent to a customer
  def accept_call(call)
    if self.available?
      self.lock_agent
      $twilio_client.account.calls.create(
        :from => "+16023888925",
        :to => "#{self.phone}",
        :url => @@router.patch_agent_call_handler_url(:format => :xml, :call_id => call.id),
        :method => "GET"
      )
    end
  end
  
  
  def display_name
    return (name ? name : email)
  end
  
  #method remove locks on an agent
  def self.delete_lock!
    $redis.del(*$redis.keys("agent:*"))
  end

  #When an agent enters a call, they will be locked so that another customer
  #cannot contact him in the middle of a call
  def lock_agent
    $redis.setex("agent:#{self.id}:locked", 600, "1")
  end
  
  #Checks to see if an agent is in the middle of a call
  def locked?
    $redis.exists("agent:#{self.id}:locked")
  end
  
  #When a call ends, the agent will be unlocked so that he may be re-entered into
  #the call queue
  def unlock_agent
    $redis.del("agent:#{self.id}:locked")
  end
  
  def email=(value)
    if value.is_a?(String)
      super(value.downcase.strip)
    end
  end
  
  def self.prioritize(params)
    params[:users].each_with_index do |user_id, index|
      user = User.find(user_id)
      user.update_attribute(:priority, index)
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
 
 #Gives list of all the current agent in the system
  def index
    @users = User.order(:priority)
    respond_to do |format|
      format.html { render :layout => "#{@empty ? "empty" : "application"}"}
      format.js
      format.json  { render :json => @users }
    end
  end
  
  #Modal to editing info about the agent
  def show
    @user = User.find(params[:id])
    respond_to do |format|
      format.html
      format.js
    end
  end
  
  def search
    @users = User.where("lcase(name) like ?", "%#{params[:term].downcase}%")
    respond_to do |format|
      format.html
      format.js
      format.json  { render :json => @users.map { |user| user.name } }
    end
  end
  
  
  #puts any changes to the agent into affect
  def update
    @user = User.find(params[:id])
    @user.update_attributes(params[:user])
    respond_to do |format|
        format.html
        format.js
        format.json  { render :json => @users }
    end
  end
  
  def sync_with_zendesk
    UserSyncr.sync_with_zendesk
    @users = User.all
    respond_to do |format|
      format.html { redirect_to users_path }
      format.js
      format.json  { render :json => @users }
    end
  end

  def prioritize
    User.prioritize(params)
    @users = User.all
    respond_to do |format|
      format.html { redirect_to users_path }
      format.js
      format.json  { render :json => @users }
    end
  end
    
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/_edit_modal.html.erb
<div class="modal hide fade" id="userModal">
</div>

app/views/users/_edit_row.html.erb
	<%= render 'user', :user => user %>

app/views/users/_form.html.erb
<%= form_for(@user,:html => { :class => "form-horizontal" }, :remote => true) do |f|%>
	<h5>Name:</h5>
	<%= f.text_field :name %>
	<h5>Callback #:</h5>
	<%= f.text_field :phone %>
	<h5>Email:</h5>
	<%= f.text_field :email %>
	<h5>Priority:</h5>
	<%= f.text_field :priority, :class => "span1" %>
	<div>
		<%= f.button :class => "btn btn-large", :style => "margin-top: 10px" %>
	</div>
<% end %>

app/views/users/_modal.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal">×</button>
	<h3>Agent Info (<%= @user.email %>)</h3>
</div>

<div class="modal-body">
	<%= render 'form'%>
</div>

<div class="modal-footer">
    <a href="#" class="btn btn-primary" data-dismiss="modal">Close</a>
</div>

app/views/users/_user.html.erb
<tr id="user_<%= user.id %>" class="user-row"<% if params[:edit] %>edited="true"<% end %>>
	<td class="name clickable" id="name_<%= user.id %>"><% if params[:edit] %><%= form_for user do |f| %><%= f.text_field :name %><% end %><% else %><span class="padded-user-column"><%= user.name %></span><% end %></td>
	<td class="phone clickable" id="phone_<%= user.id %>"><% if params[:edit] %><%= form_for user do |f| %><%= f.text_field :phone %><% end %><% else %><span class="padded-user-column"><%= user.phone %></span><% end %></td>
	<td class="email clickable" id="email_<%= user.id %>"><% if params[:edit] %><%= form_for user do |f| %><%= f.text_field :email %><% end %><% else %><span class="padded-user-column"><%= user.email %></span><% end %></td>
	<td class="availability">
		<div class="btn-group">
			<button class="btn btn-small dropdown-toggle" data-toggle="dropdown" id="user_<%= user.id %>_available" style="width: 100%; text-align: left;"><%= user.availability %> <span class="caret" style="float: right"></span></button>
    <ul class="dropdown-menu">
			<% User::AVAILABILITY.each do |available| %>
	      <li><%= link_to_function "#{available}", "updateAvailabilityOfAgent(#{user.id}, '#{escape_javascript(available)}')" %></li>
		<% end %>
		</ul>
		</div>
	</td>
</tr>

app/views/users/edit.html.erb
<div class="new_user">
	<h1>Edit Agent</h1>
	<%= link_to "Agent Settings", users_path() %>
	<%= render 'form' %>
</div>

app/views/users/index.html.erb
<div class="user-settings">
<h1 class="agent_header">Agent Settings</h1>

	<table id="users" class="table call-padded table-clickable">
		<thead>
			<tr>
				<th class="name"><span class="icon-user"></span> Name</th>
				<th class="phone"><span class="icon-hand-right"></span> Callback #</th>
				<th class="email"><span class="icon-envelope"></span> Email</th>
				<th class="availability"><span class="icon-flag"></span> Available</th>
			</tr>
		</thead>
		<tbody>
		<tr>
			<% @users.each do |user| %>
			<%= render 'edit_row', :user => user %>
			<% end %>
			</tr>
		</tbody>
	</table>	
	
	<div class="sync_users">
		<%= button_to "Sync App With Zendesk", sync_with_zendesk_users_path, :class => "btn btn-danger", :confirm => 'Are you sure you want to remove users?' %>
	</div>
</div>


<%= render 'edit_modal' %>

<script>
	allow_agent_sort();
</script>

app/views/users/new.html.erb
<div class="new_user">
	<h1>New Agent</h1>
	<br>
	<%= link_to "Agent Settings", users_path() %>
	<br>
	<br>
	<br>
	<%= render 'form' %>
</div>

app/views/users/show.html.erb
<!-- <div class="modal-header">
  <button type="button" class="close" data-dismiss="modal">×</button>
	<h3>Agent Info (<%= @user.email %>)</h3>
</div>

<div class="modal-body">
	<%= render 'form'%>
</div>

<div class="modal-footer">
    <a href="#" class="btn btn-primary" data-dismiss="modal">Close</a>
</div> -->

app/views/users/show.js.erb
// $("#userModal").html("<%= escape_javascript(render('modal', :user => @user)) %>");
// $('#userModal').modal('show');

// $("tr#user_<%= @user.id %>").html(.html());

user_row = $("tr#user_<%= @user.id %> td");
new_obj = $("<%= escape_javascript(render(@user)) %>");
new_obj.find("td").each(function(index) { $(user_row[index]).html($(this).html()) })

app/views/users/update.js.erb
// $("#userModal").html("<%= escape_javascript(render('modal')) %>");
// $("#userModal .modal-body").prepend("<div class=\"alert alert-success\">User information has been updated.</div>");
$("#main #error-alert").detach();
$("tr#user_<%= @user.id %>").replaceWith("<%= escape_javascript(render(@user)) %>");
magic();